### ISSUE TITLE
missing “malis ” 

### ISSUE THREAD

**Issue by bsjaaa** [bgpantojar/topo_crack_detection#1]
First of all thank you for your contribution, it is very valuable.
  When I used your code, I encountered the following problem. Can you provide relevant documents? I would appreciate it.

Traceback (most recent call last):
  File "C:\Users\xiaobaia\Desktop\topo_crack_detection-master\src\main.py", line 33, in <module>
    from newloss import MALISLoss_window_pos
  File "C:\Users\xiaobaia\Desktop\topo_crack_detection-master\src\newloss.py", line 23, in <module>
    import malis as m
  File "C:\Users\xiaobaia\Desktop\topo_crack_detection-master\src\malis\__init__.py", line 1, in <module>
    from .malis import *
ModuleNotFoundError: No module named 'malis.malis'

**Comment by bgpantojar** [comment]
Hello,

Notice the repository was tested on Ubuntu 18 OS system. 

It seems that you are running it on Windows. In this case you should build the extension files using the setup.py script (for Ubuntu the are already built placed on src/malis).

To build the extension files try something like: `python setup.py build_ext --inplace`

Bryan

**Comment by bsjaaa** [comment]
That worked for me. Thank you very much
